default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: pretty-format-json
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [--line-length=88]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=88]

-   repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
